#!/bin/sh

## Make sure to have installed NEURON compatible with CoreNEURON
## Compile CoreNEURON with GPU support
## Make sure $PATH is correctly set and modules are loaded

nrnivmodl .
nrnivmodl-core .

names="deriv gf kin conc watch"

for i in $names ; do
  x86_64/special test${i}.hoc
  cat out[0-9].dat | sort -k 1n,1n -k 2n,2n > out_nrn_${i}.spk
  rm out[0-9].dat
done

for i in $names ; do
  srun -n 1 x86_64/special-core -d test${i}dat --cell-permute 1 -e 100 --gpu --mpi
  cat out.dat | sort -k 1n,1n -k 2n,2n > out_gpu_${i}.spk
  rm out.dat
done

for i in $names ; do
  diff -w -q out_nrn_${i}.spk out_gpu_${i}.spk
done
